/****************************************************************************************
 * @file    EXTI.c
 * @author  Mahmoud Karam (ma.karam272@gmail.com)
 * @brief   External Interrupts (EXTI) driver for Atmega128 microcontroller.
 * @version 1.0.0
 * @date 2022-02-05
 * @details There are two types of interrupts:
 *             1. Interrupts that are generated by the peripheral (HW interrupt).
 *             2. Interrupts that are generated by the application (SW interrupt).
 *             The application can generate interrupts by calling the function
 *              EXTI_GenerateSWInterrupt().
 *            The peripheral can generate interrupts by calling the function
 *             EXTI_GenerateHWInterrupt().
 *           The application can clear the interrupt by calling the function
 *            EXTI_ClearSWInterrupt().
 *           
 *          There are 4 modes of interrupt generation:
 *              1. Interrupt on falling edge.
 *              2. Interrupt on rising edge.
 *              3. Interrupt on both edges (On Change).
 *              4. Interrupt on active level.
 *          When edge triggered, the interrupt is triggered only once when a 
 *          falling edge from high logic level to low logic level happens. 
 *          Only once even if the signal stays low, or goes high again.
 *          But when level triggered, the interrupt is triggered repeatedly while 
 *          the logic level is low, continuously, until the logic level goes high again.
 *          So you really don't want to re-enable interrupts in a ISR which is 
 *          triggered on low level. And if the level is low, not much mainline code 
 *          gets chance to run, because the ISR is run repeatedly.
 *          So yes, basically low level and falling edge types of interrupts are 
 *          both triggered when signal goes from high to low. Difference is that 
 *          other gets triggered only once at the falling edge, the other triggers 
 *          constantly while the level is low.
 * @note INT0 to INT3 do not have (On Change mode)
 * @note INT4 to INT7 need IO clock if configured as edge triggered.
 * @note INT0 to INT3 use Asynchronous clock. So, they can wake up the MCU from 
 *      sleep mode at any mode.
 * @todo Debug configuration of INT4 to INT7 as edge triggered not working.
 * 
 * @copyright Copyright (c) 2022
 * 
 */
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "EXTI_reg.h"
#include "SREG.h"
#include "GIE.h"
#include "EXTI.h"
#include "EXTI_cfg.h"

/*--------------------------------------------------------------------------*/
/*                              CALLBACKS                                   */
/*--------------------------------------------------------------------------*/
static void (* INT0_callbackPtr)(void) = NULL;
static void (* INT1_callbackPtr)(void) = NULL;
static void (* INT2_callbackPtr)(void) = NULL;
static void (* INT3_callbackPtr)(void) = NULL;
static void (* INT4_callbackPtr)(void) = NULL;
static void (* INT5_callbackPtr)(void) = NULL;
static void (* INT6_callbackPtr)(void) = NULL;
static void (* INT7_callbackPtr)(void) = NULL;

/*--------------------------------------------------------------------------*/
/*                            ISR FUNCTIONS                                 */
/*--------------------------------------------------------------------------*/

/****************************************************************************
 * ISR of INT0 
 ****************************************************************************/
void __vector_1(void) __attribute__((signal));
void __vector_1(void) {
    if(NULL != INT0_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT0_callbackPtr();
    }else {
        /* DEBUG    */
    }
    
    /* clear flag */
    SET_BIT(EIFR, INTF0);
    #if(NESTING == NESTING_DISABLED)
    GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT1 
 ****************************************************************************/
void __vector_2(void) __attribute__((signal));
void __vector_2(void) {
    
    if(NULL != INT1_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT1_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */    
    SET_BIT(EIFR, INTF1);
    #if(NESTING == NESTING_DISABLED)
        GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT2 
 ****************************************************************************/
void __vector_3(void) __attribute__((signal));
void __vector_3(void) {
    if(NULL != INT2_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT2_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */
    SET_BIT(EIFR, INTF2);
    #if(NESTING == NESTING_DISABLED)
        GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT3 
 ****************************************************************************/
void __vector_4(void) __attribute__((signal));
void __vector_4(void) {
    if(NULL != INT3_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT3_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */
    SET_BIT(EIFR, INTF3);
    #if(NESTING == NESTING_DISABLED)
        GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT4 
 ****************************************************************************/
void __vector_5(void) __attribute__((signal));
void __vector_5(void) {
    if(NULL != INT4_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT4_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */
    SET_BIT(EIFR, INTF4);
    #if(NESTING == NESTING_DISABLED)
    GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT5 
 ****************************************************************************/
void __vector_6(void) __attribute__((signal));
void __vector_6(void) {
    if(NULL != INT5_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT5_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */
    SET_BIT(EIFR, INTF5);
    #if(NESTING == NESTING_DISABLED)
    GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT6 
 ****************************************************************************/
void __vector_7(void) __attribute__((signal));
void __vector_7(void) {
    if(NULL != INT6_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT6_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */
    SET_BIT(EIFR, INTF6);
    #if(NESTING == NESTING_DISABLED)
    GIE_Enable();
    #endif
}

/****************************************************************************
 * ISR of INT7 
 ****************************************************************************/
void __vector_8(void) __attribute__((signal));
void __vector_8(void) {
    if(NULL != INT7_callbackPtr) {
        #if(NESTING == NESTING_DISABLED)
        GIE_Disable();
        #endif
        INT7_callbackPtr();
    }else {
        /* DEBUG    */
    }

    /* clear flag */
    SET_BIT(EIFR, INTF7);
    #if(NESTING == NESTING_DISABLED)
    GIE_Enable();
    #endif
}

/*----------------------------------------------------------------------------*/
/*                           PRIVATE FUNCTION                                 */                              
/*----------------------------------------------------------------------------*/
static void EXTI_SetSensitivity(const EXTI_t extiNumber, const EXTI_SENSITIVITY_t sensitivity) {
    u8 eimsk = EIMSK;
    
    EIMSK = 0;

    switch (extiNumber) {
        case EXTI_0:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRA, ISC00);
                CLR_BIT(EICRA, ISC01);
            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRA, ISC00);
                SET_BIT(EICRA, ISC01);
            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRA, ISC00);
                SET_BIT(EICRA, ISC01);
            }else {
                /* DEBUG    */
            }
            break;
        
        case EXTI_1:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRA, ISC10);
                CLR_BIT(EICRA, ISC11);
            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRA, ISC10);
                SET_BIT(EICRA, ISC11);
            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRA, ISC10);
                SET_BIT(EICRA, ISC11);
            }else {
                /* DEBUG    */
            }
            break;
        
        case EXTI_2:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRA, ISC20);
                CLR_BIT(EICRA, ISC21);
            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRA, ISC20);
                SET_BIT(EICRA, ISC21);
            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRA, ISC20);
                SET_BIT(EICRA, ISC21);
            }else {
                /* DEBUG    */
            } 
            break;
        
        case EXTI_3:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRA, ISC30);
                CLR_BIT(EICRA, ISC31);
            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRA, ISC30);
                SET_BIT(EICRA, ISC31);
            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRA, ISC30);
                SET_BIT(EICRA, ISC31);
            }else {
                /* DEBUG    */
            }
            break;
        
        case EXTI_4:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRB, ISC40);
                CLR_BIT(EICRB, ISC41);

            }else if(LOGIC_CHANGE == sensitivity) {
                SET_BIT(EICRB, ISC40);
                CLR_BIT(EICRB, ISC41);

            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRB, ISC40);
                SET_BIT(EICRB, ISC41);

            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRB, ISC40);
                SET_BIT(EICRB, ISC41);

            }else {
                /* DEBUG    */
            }
            break;
        
        case EXTI_5:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRB, ISC50);
                CLR_BIT(EICRB, ISC51);

            }else if(LOGIC_CHANGE == sensitivity) {
                SET_BIT(EICRB, ISC50);
                CLR_BIT(EICRB, ISC51);

            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRB, ISC50);
                SET_BIT(EICRB, ISC51);

            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRB, ISC50);
                SET_BIT(EICRB, ISC51);
                
            }else {
                /* DEBUG    */
            }
            break;

        case EXTI_6:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRB, ISC60);
                CLR_BIT(EICRB, ISC61);
            }else if(LOGIC_CHANGE == sensitivity) {
                SET_BIT(EICRB, ISC60);
                CLR_BIT(EICRB, ISC61);
            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRB, ISC60);
                SET_BIT(EICRB, ISC61);
            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRB, ISC60);
                SET_BIT(EICRB, ISC61);
            }else {
                /* DEBUG    */
            }
            break;
        
        case EXTI_7:
            if(LOW_LEVEL_DETECT == sensitivity) {
                CLR_BIT(EICRB, ISC70);
                CLR_BIT(EICRB, ISC71);
            }else if(LOGIC_CHANGE == sensitivity) {
                SET_BIT(EICRB, ISC70);
                CLR_BIT(EICRB, ISC71);
            }else if(RISING_EDGE == sensitivity) {
                SET_BIT(EICRB, ISC70);
                SET_BIT(EICRB, ISC71);
            }else if(FALLING_EDGE == sensitivity) {
                CLR_BIT(EICRB, ISC70);
                SET_BIT(EICRB, ISC71);
            }else {
                /* DEBUG    */
            }
            break;

        default:
            /* DEBUG    */
            break;
    }

    /* Enabling other interrupts   */
    (EIMSK) |= eimsk;
}

static void EXTI_SetCallback(const EXTI_t extiNumber, void (* const const callbackPtr)(void)) {
    switch(extiNumber) {
        case EXTI_0:
            INT0_callbackPtr = callbackPtr;
            break;
        case EXTI_1:
            INT1_callbackPtr = callbackPtr;
            break;
        case EXTI_2:
            INT2_callbackPtr = callbackPtr;
            break;
        case EXTI_3:
            INT3_callbackPtr = callbackPtr;
            break;
        case EXTI_4:
            INT4_callbackPtr = callbackPtr;
            break;
        case EXTI_5:
            INT5_callbackPtr = callbackPtr;
            break;
        case EXTI_6:
            INT6_callbackPtr = callbackPtr;
            break;
        case EXTI_7:
            INT7_callbackPtr = callbackPtr;
            break;
        default:
            /* DEBUG    */
            break;
    }
}


/*----------------------------------------------------------------------------*/
/*                          PUBLIC FUNCTIONS                                  */
/*----------------------------------------------------------------------------*/

/******************************************************************************
 * @details Initialize an external interrupt pin as input pin and set the 
 *****************************************************************************/
void EXTI_Init(const EXTI_t extiNumber, const EXTI_SENSITIVITY_t  sensitivity, void (* const callbackPtr)(void)) {
    /* Disabling global interrupt flag  */
    GIE_Disable();       /* cli()    */

    EXTI_SetSensitivity(extiNumber, sensitivity);

    /* Enabling interrupt   */
    EXTI_EnableExternalInterrupt(extiNumber);

    /* Setting callback function   */
    EXTI_SetCallback(extiNumber, callbackPtr);

    /* Enabling global interrupt flag  */
    GIE_Enable();    /* sei  */
}

/******************************************************************************
 * @details Enable external interrupt pin
 *****************************************************************************/
void EXTI_EnableExternalInterrupt(const EXTI_t extiNumber) {
    u8 sreg = SREG;

    /* Disable global interrupt */
    GIE_Disable();
    
    /* Enable interrupt */
    switch(extiNumber) {
        case EXTI_0:
            SET_BIT(EIFR, INTF0);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT0);
            break;
        case EXTI_1:
            SET_BIT(EIFR, INTF1);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT1);
            break;
        case EXTI_2:
            SET_BIT(EIFR, INTF2);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT2);
            break;
        case EXTI_3:
            SET_BIT(EIFR, INTF3);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT3);
            break;
        case EXTI_4:
            SET_BIT(EIFR, INTF4);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT4);
            break;
        case EXTI_5:
            SET_BIT(EIFR, INTF5);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT5);
            break;
        case EXTI_6:
            SET_BIT(EIFR, INTF6);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT6);
            break;
        case EXTI_7:
            SET_BIT(EIFR, INTF7);    /* Clear interrupt flag */
            SET_BIT(EIMSK, INT7);
            break;
        default:
            /* DEBUG    */
            break;
    }

    SREG = sreg;
}

void EXTI_DisableExternalInterrupt(const EXTI_t extiNumber) {
    switch (extiNumber) {
        case EXTI_0:
            CLR_BIT(EIMSK, INT0);
            break;
        case EXTI_1:
            CLR_BIT(EIMSK, INT1);
            break;
        case EXTI_2:
            CLR_BIT(EIMSK, INT2);
            break;
        case EXTI_3:
            CLR_BIT(EIMSK, INT3);
            break;
        case EXTI_4:
            CLR_BIT(EIMSK, INT4);
            break;
        case EXTI_5:
            CLR_BIT(EIMSK, INT5);
            break;
        case EXTI_6:
            CLR_BIT(EIMSK, INT6);
            break;
        case EXTI_7:
            CLR_BIT(EIMSK, INT7);
            break;
        default:
            /* DEBUG    */
            break;
    }
}


